BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[mdWorking] ALTER COLUMN [startWorktime] NVARCHAR(1000) NOT NULL;
ALTER TABLE [dbo].[mdWorking] ALTER COLUMN [stopWorktime] NVARCHAR(1000) NOT NULL;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
