BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[employee] ADD [active] BIT NOT NULL CONSTRAINT [employee_active_df] DEFAULT 1;

-- AlterTable
ALTER TABLE [dbo].[user] ADD [active] BIT NOT NULL CONSTRAINT [user_active_df] DEFAULT 1;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
